/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.soclosetoheaven.client.ui.auth;

import javax.swing.*;
import java.awt.event.ActionEvent;

/**
 *
 * @author Дмитрий
 */
public class LoginRegisterContainerPanel extends javax.swing.JPanel {

    /**
     * Creates new form loginRegisterContainerPanel
     */
    public LoginRegisterContainerPanel() {
        initComponents();
        registerPanel.setVisible(false);
        loginPanel.getRegisterButton().addActionListener(this::switchPanels);
        registerPanel.getBackButton().addActionListener(this::switchPanels);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel = new com.soclosetoheaven.client.ui.auth.LoginPanel();
        registerPanel = new com.soclosetoheaven.client.ui.auth.RegisterPanel();

        setLayout(new javax.swing.OverlayLayout(this));
        add(loginPanel);
        add(registerPanel);
    }// </editor-fold>//GEN-END:initComponents

    public void setDefaultText() {
        loginPanel.setDefaultText();
        registerPanel.setDefaultText();
    }
    public void switchPanels(ActionEvent event) {
        loginPanel.setVisible(!loginPanel.isVisible());
        registerPanel.setVisible(!loginPanel.isVisible());
    }


    public LoginPanel getLoginPanel() {
        return loginPanel;
    }

    public RegisterPanel getRegisterPanel() {
        return registerPanel;
    }

    public JButton getLoginButton() {
        return loginPanel.getLoginButton();
    }

    public JButton getRegisterButton() {
        return registerPanel.getRegisterButton();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.soclosetoheaven.client.ui.auth.LoginPanel loginPanel;
    private com.soclosetoheaven.client.ui.auth.RegisterPanel registerPanel;
    // End of variables declaration//GEN-END:variables

}
