/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.soclosetoheaven.client.ui.application;

import com.soclosetoheaven.client.ui.model.DragonMapModel;
import com.soclosetoheaven.common.model.Dragon;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author Дмитрий
 */
public class ElementsMapPanel extends javax.swing.JPanel {

    /**
     * Creates new form ElementsMapPanel
     */
    public ElementsMapPanel() {
        this.dragonModelMap = new HashMap<>();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
      private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        innerPanel = new javax.swing.JLayeredPane();
        map = new javax.swing.JLabel();

        scrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        scrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        ImageIcon mapIcon = new javax.swing.ImageIcon(getClass().getResource("/images/world-map.png"));
        map.setIcon(mapIcon); // NOI18N
        innerPanel.setPreferredSize(new Dimension(mapIcon.getIconWidth(), mapIcon.getIconHeight()));
        map.setSize(new Dimension(mapIcon.getIconWidth(), mapIcon.getIconHeight()));
        innerPanel.add(map, JLayeredPane.DEFAULT_LAYER);


        scrollPane.setViewportView(innerPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(scrollPane, GroupLayout.DEFAULT_SIZE, mapIcon.getIconWidth(), Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPane, javax.swing.GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, mapIcon.getIconHeight(), Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents



    public void drawDragon(Dragon dragon, MouseAdapter adapter) {
        DragonMapModel dragonMapModel = new DragonMapModel(dragon);
        dragonMapModel.addMouseListener(adapter);
        innerPanel.add(dragonMapModel, JLayeredPane.DRAG_LAYER);
        dragonModelMap.put(dragon.getID(), dragonMapModel);
        dragonMapModel.defaultPaint();
    }


    public void deleteDragon(Dragon dragon) {
        DragonMapModel dragonMapModel = dragonModelMap.get(dragon.getID());
        dragonMapModel.prepareForRemoving(innerPanel);
        dragonModelMap.remove(dragon.getID());

    }


    public void updateDragon(Dragon dragon) {
        dragonModelMap.get(dragon.getID()).updateDragon(dragon);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane innerPanel;
    private javax.swing.JLabel map;
    private javax.swing.JScrollPane scrollPane;


    // End of variables declaration//GEN-END:variables

    private final Map<Integer, DragonMapModel> dragonModelMap;
}
